### ISSUE TITLE
http://192.168.0.108:8080/gauche show "Not tar files" in Browser

### ISSUE THREAD

**Issue by APIPLM** [lassik/scheme-eval-server#1]
Start up the server. It can access by the `eval-client.scm `client. But in the Browser, it show up "Not tar files"

**Comment by lassik** [comment]
You can't use it interactively from a browser since you have to make a HTTP request that has a tar archive in the request body. `eval-client.scm` does that. You could also use `curl` or something.

**Comment by lassik** [comment]
It should be possible to write a HTML form that calls JavaScript to make a tar archive and send it. Then it would work from the browser too.

**Comment by APIPLM** [comment]
`curl -I -H 'Content-Type: application/x-tar' -H 'accept: application/x-tar' http://192.168.0.108:8080/gauche`
The output in the following
```
HTTP/1.1 200 OK
Content-Type: text/html
Server: Spiffy/6.3 (Running on CHICKEN 5.2.1)
Content-Length: 2048
Date: Mon, 20 Sep 2021 00:28:22 GMT
```
why in the output,  the value of Content-Type still text/html


`curl -H 'Content-Type: application/x-tar' -H 'accept: application/x-tar' http://192.168.0.108:8080/gauche`
The output in the following
`proc/fd/10002104000000000000000000000001400000000000012420 0ustar00rootroot00000000000000Hello gauche`

**Comment by APIPLM** [comment]
In JS, I tried the `XMLHttpRequest` of Browser, it could not work.
```
    let xhr = new XMLHttpRequest();
    xhr.setRequestHeader('Content-Type', 'application/x-tar');
    xhr.setRequestHeader('accept', 'application/x-tar');
    
    xhr.open('POST', "http://192.168.0.108:8080/gauche", true);
    xhr.send();


    xhr.onreadystatechange = processRequest;

    function processRequest(e) {
    if (xhr.readyState == 4 && xhr.status == 200) {

        document.querySelector("#ipText").innerHTML = xhr.responseText;
    }
    }
```

@jcubic, do you have time to look at it.

**Comment by jcubic** [comment]
I would try to fetch in the browser, but I'm not sure how to run the application. I'm not sure how to run the application. How do you run it?

**Comment by APIPLM** [comment]
start up the server by `./csi -s eval-server.scm`.  Then It can access in the Bowser like http://localhost:3000/gauche

**Comment by jcubic** [comment]
I don't see scm files in the repo, there is only a library std file.
When I try to execute it I've got error:
```bash
$ csi -s eval-server.sld 

Error: toplevel definition in non-toplevel context for variable: implementations
```

I don't know how to import the library from a local file, do I need to create eval-server.scm. Maybe it's worth adding missing files.

**Comment by lassik** [comment]
> why in the output, the value of Content-Type still text/html

That's a bug. Thanks for reporting it; fixed.

`cat /dev/zero | head -c 1024 | curl --silent --verbose --data-binary @- -H 'Content-Type: application/x-tar' -H 'Accept: application/x-tar' http://localhost:3000/gauche`

Now shows:

```
< HTTP/1.1 200 OK
< Content-Type: application/x-tar
```

**Comment by lassik** [comment]
@jcubic:

```
$ chicken-install csm
$ csm -r7rs -program eval-client -ignore surveys
$ csm -r7rs -program eval-server -ignore surveys
$ PORT=3000 ./eval-server &
$ ./eval-client
```

I just started working on these programs yesterday, so almost nothing is ready yet.

**Comment by APIPLM** [comment]
Yes.`csm `egg just got released.  That is how the script in Chicken is built in Chicken build system. I am trying to figure out how `csm `egg check the dependence when the script and the module to invoke the third C lib. Then check the correct version in the /usr/lib folder.

**Comment by lassik** [comment]
I don't know. `pkg-config` is a good way to do that, but it doesn't seem that `csm` is using it.

**Comment by APIPLM** [comment]
Yes. The `csm` usage case is for the top level program (applications) until now. Looking at  `man pkg-config`, it likes that to look up the meta information of the installed libraries. From this point, at least it like have two kind of meta information, as people working with chicken eggs. The question come out, how can both of them be maintained as they messed up. Even it is not related to what this issue is. But sound like deserve to pay an attention.
